using System;

namespace Domain.Enums.JobEnums
{
    public enum JobTitles
    {
        AccountingSpecialist = 0,
        FinancialAnalyst = 1,
        TaxExpert = 2,
        HRSpecialist = 3,
        HRAssistant = 4,
        PersonnelManager = 5,
        TrainingSpecialist = 6,
        InventoryManager = 7,
        StockControlSpecialist = 8,
        LogisticsAnalyst = 9,
        MachineMaintenanceSpecialist = 10,
        Electrician = 11,
        MaintenanceEngineer = 12,
        ITSpecialist = 13,
        NetworkEngineer = 14,
        SoftwareDeveloper = 15,
        BackendDeveloper = 16,
        FrontendDeveloper = 17,
        MachineLearningEngineer = 18,
        DatabaseAdministrator = 19,
        ITManager = 20,
        HardwareTechnician = 21,
        SupplyChainManager = 22,
        WarehouseClerk = 23,
        TransportationCoordinator = 24,
        LogisticsOperationSpecialist = 25,
        Operator = 26,
        Engineer = 27,
        MaintenanceSpecialist = 28,
        QualityControlSpecialist = 29,
        ProductionPlanningSpecialist = 30,
        ProductionPlanningEngineer = 31,
        PlanningCoordinator = 32,
        InventoryAnalyst = 33,
        QualityControlEngineer = 34,
        TestOperator = 35,
        QualityManager = 36,
        Researcher = 37,
        ProductDevelopmentEngineer = 38,
        ProjectManager = 39,
        OccupationalSafetySpecialist = 40,
        FireSafetyCoordinator = 41,
        SalesRepresentative = 42,
        SalesManager = 43,
        MarketingSpecialist = 44,
    }
}
